### PR TITLE
Moving from SDK images to runtime images

### PR DESCRIPTION
**Pull request by michimune**

### CODE REVIEW

**Comment by michimune** [comment]
You are absolutely right. I actually felt that we should rename the images before merging.

Option A)
1.0.0-msbuild -> 1.0-msbuild because the runtime uses 1.0, not 1.0.x
1.1.0-msbuild -> 1.1-msbuild because the runtime uses 1.1, not 1.1.x

Option B)
1.0.0-msbuid -> 1.0.4-msbuild and change the base image to 1.0.4-runtime
1.1.0-msbuild -> 1.1.1-msbuild and change the base image to 1.1.1-runtime

**Comment by nickwalkmsft** [comment]
@naziml Can you comment on this as well? I'm not sure what you had in mind with regards to cadence, possible breaking changes, or whether or not we want to base images on labels that the .NET team updates vs. labels that don't.

**Comment by nickwalkmsft** [comment]
I'm going to commandeer this PR and work its core concept into a new changeset, after discussing offline.

Basically we'll go with Michi's Option B above, deriving from the newest images for both runtimes, using the fully specified image names (ex: _1.1.1-runtime_, as opposed to _1.1-runtime_, _1-runtime_ or _runtime_, which all currently map to the same image but will get updated later on as new releases are created)

Covered in an email, but here's the strategy going forward:

•	New blessed images for 1.1.1 and 1.0.4 runtimes (based on image tags 1.0.4-runtime and 1.1.1-runtime). We will need to get these into the dropdown in the UX as well.
•	We can keep the existing blessed .NET Core image we have right now around for a while for those using it (I believe it's 1.0.0-preview2)
•	Install the 1.0.1 SDK into the Kudu image and support only that. Unlike Windows App Service, we will support only the newest SDK, which does not include project.json.

**Comment by michimune** [comment]
Closing the PR as per discussion.

**Pull request closed without merging**
